settings:
    timezone: Europe/Istanbul

database:
    connection: mysql
    connections:
        mysql:
            driver: mysql
            host: localhost
            database:
            username:
            password:
            charset: utf8
            collation: utf8_unicode_ci
            prefix: ''
            strict: false